// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// load_ld.h
doubles_matrix<> load_ld(std::string prefix, int chromosome, int total_snps, integers snp_index);
extern "C" SEXP _LAVA_load_ld(SEXP prefix, SEXP chromosome, SEXP total_snps, SEXP snp_index) {
  BEGIN_CPP11
    return cpp11::as_sexp(load_ld(cpp11::as_cpp<cpp11::decay_t<std::string>>(prefix), cpp11::as_cpp<cpp11::decay_t<int>>(chromosome), cpp11::as_cpp<cpp11::decay_t<int>>(total_snps), cpp11::as_cpp<cpp11::decay_t<integers>>(snp_index)));
  END_CPP11
}
// load_plink.h
list load_plink(std::string prefix, int total_snps, int total_indiv, integers snp_index, list parameters);
extern "C" SEXP _LAVA_load_plink(SEXP prefix, SEXP total_snps, SEXP total_indiv, SEXP snp_index, SEXP parameters) {
  BEGIN_CPP11
    return cpp11::as_sexp(load_plink(cpp11::as_cpp<cpp11::decay_t<std::string>>(prefix), cpp11::as_cpp<cpp11::decay_t<int>>(total_snps), cpp11::as_cpp<cpp11::decay_t<int>>(total_indiv), cpp11::as_cpp<cpp11::decay_t<integers>>(snp_index), cpp11::as_cpp<cpp11::decay_t<list>>(parameters)));
  END_CPP11
}
// load_plink.h
list compute_ld(std::string prefix, int total_snps, int total_indiv, integers snp_index, list parameters);
extern "C" SEXP _LAVA_compute_ld(SEXP prefix, SEXP total_snps, SEXP total_indiv, SEXP snp_index, SEXP parameters) {
  BEGIN_CPP11
    return cpp11::as_sexp(compute_ld(cpp11::as_cpp<cpp11::decay_t<std::string>>(prefix), cpp11::as_cpp<cpp11::decay_t<int>>(total_snps), cpp11::as_cpp<cpp11::decay_t<int>>(total_indiv), cpp11::as_cpp<cpp11::decay_t<integers>>(snp_index), cpp11::as_cpp<cpp11::decay_t<list>>(parameters)));
  END_CPP11
}
// load_plink.h
doubles_matrix<> compute_info(std::string prefix, int total_snps, int total_indiv, integers snp_index);
extern "C" SEXP _LAVA_compute_info(SEXP prefix, SEXP total_snps, SEXP total_indiv, SEXP snp_index) {
  BEGIN_CPP11
    return cpp11::as_sexp(compute_info(cpp11::as_cpp<cpp11::decay_t<std::string>>(prefix), cpp11::as_cpp<cpp11::decay_t<int>>(total_snps), cpp11::as_cpp<cpp11::decay_t<int>>(total_indiv), cpp11::as_cpp<cpp11::decay_t<integers>>(snp_index)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_LAVA_compute_info", (DL_FUNC) &_LAVA_compute_info, 4},
    {"_LAVA_compute_ld",   (DL_FUNC) &_LAVA_compute_ld,   5},
    {"_LAVA_load_ld",      (DL_FUNC) &_LAVA_load_ld,      4},
    {"_LAVA_load_plink",   (DL_FUNC) &_LAVA_load_plink,   5},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_LAVA(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
