# Generated by cpp11: do not edit by hand

load_ld <- function(prefix, chromosome, total_snps, snp_index) {
  .Call(`_LAVA_load_ld`, prefix, chromosome, total_snps, snp_index)
}

load_plink <- function(prefix, total_snps, total_indiv, snp_index, parameters) {
  .Call(`_LAVA_load_plink`, prefix, total_snps, total_indiv, snp_index, parameters)
}

compute_ld <- function(prefix, total_snps, total_indiv, snp_index, parameters) {
  .Call(`_LAVA_compute_ld`, prefix, total_snps, total_indiv, snp_index, parameters)
}

compute_info <- function(prefix, total_snps, total_indiv, snp_index) {
  .Call(`_LAVA_compute_info`, prefix, total_snps, total_indiv, snp_index)
}
